<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[I am in onStart method LoginTest]]>
    </line>
    <line>
      <![CDATA[Tests are starting!]]>
    </line>
    <line>
      <![CDATA[EmptyUserEmptyPassword test is starting.]]>
    </line>
    <line>
      <![CDATA[ĐÂY LÀ LOG ]]>
    </line>
    <line>
      <![CDATA[EmptyUserEmptyPassword test is failed.]]>
    </line>
    <line>
      <![CDATA[InvalidUserNameInvalidPassword test is starting.]]>
    </line>
    <line>
      <![CDATA[ĐÂY LÀ LOG ]]>
    </line>
    <line>
      <![CDATA[InvalidUserNameInvalidPassword test is succeed.]]>
    </line>
    <line>
      <![CDATA[Tests are ending!]]>
    </line>
  </reporter-output>
  <suite name="N11 Test Suite" duration-ms="14267" started-at="2022-08-02T08:04:01 ICT" finished-at="2022-08-02T08:04:15 ICT">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="14267" started-at="2022-08-02T08:04:01 ICT" finished-at="2022-08-02T08:04:15 ICT">
      <class name="tests.LoginTests">
        <test-method status="PASS" signature="deleteAllFilesInReportNGScreenshot()[pri:0, instance:tests.LoginTests@2e27d72f]" name="deleteAllFilesInReportNGScreenshot" is-config="true" duration-ms="19" started-at="2022-08-02T08:04:01 ICT" finished-at="2022-08-02T08:04:01 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAllFilesInReportNGScreenshot -->
        <test-method status="PASS" signature="classLevelSetup()[pri:0, instance:tests.LoginTests@2e27d72f]" name="classLevelSetup" is-config="true" duration-ms="3228" started-at="2022-08-02T08:04:02 ICT" finished-at="2022-08-02T08:04:05 ICT">
          <reporter-output>
            <line>
              <![CDATA[Tests are starting!]]>
            </line>
          </reporter-output>
        </test-method> <!-- classLevelSetup -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.LoginTests@2e27d72f]" name="methodLevelSetup" is-config="true" duration-ms="13" started-at="2022-08-02T08:04:05 ICT" finished-at="2022-08-02T08:04:05 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="FAIL" signature="EmptyUserEmptyPassword(java.lang.reflect.Method)[pri:1, instance:tests.LoginTests@2e27d72f]" name="EmptyUserEmptyPassword" duration-ms="5275" started-at="2022-08-02T08:04:05 ICT" description="Invalid Login Scenario with empty username and password." finished-at="2022-08-02T08:04:10 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTests.EmptyUserEmptyPassword(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Vo Thi Thu Phuoc] but found [nopCommerce demo store. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Vo Thi Thu Phuoc] but found [nopCommerce demo store. Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.LoginTests.EmptyUserEmptyPassword(LoginTests.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[EmptyUserEmptyPassword test is starting.]]>
            </line>
            <line>
              <![CDATA[ĐÂY LÀ LOG ]]>
            </line>
            <line>
              <![CDATA[EmptyUserEmptyPassword test is failed.]]>
            </line>
          </reporter-output>
        </test-method> <!-- EmptyUserEmptyPassword -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.LoginTests@2e27d72f]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2022-08-02T08:04:10 ICT" finished-at="2022-08-02T08:04:10 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="InvalidUserNameInvalidPassword(java.lang.reflect.Method)[pri:0, instance:tests.LoginTests@2e27d72f]" name="InvalidUserNameInvalidPassword" duration-ms="4117" started-at="2022-08-02T08:04:10 ICT" description="Invalid Login Scenario with wrong username and password." finished-at="2022-08-02T08:04:15 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTests.InvalidUserNameInvalidPassword(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[InvalidUserNameInvalidPassword test is starting.]]>
            </line>
            <line>
              <![CDATA[ĐÂY LÀ LOG ]]>
            </line>
            <line>
              <![CDATA[InvalidUserNameInvalidPassword test is succeed.]]>
            </line>
          </reporter-output>
        </test-method> <!-- InvalidUserNameInvalidPassword -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:tests.LoginTests@2e27d72f]" name="teardown" is-config="true" duration-ms="581" started-at="2022-08-02T08:04:15 ICT" finished-at="2022-08-02T08:04:15 ICT">
          <reporter-output>
            <line>
              <![CDATA[Tests are ending!]]>
            </line>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.LoginTests -->
    </test> <!-- LoginTest -->
  </suite> <!-- N11 Test Suite -->
</testng-results>
